[package]
name = "cargo-ebuild"
version = "0.1.7"
authors = ["Doug Goldstein <cardoe@cardoe.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/cardoe/cargo-ebuild"
homepage = "https://github.com/cardoe/cargo-ebuild"
documentation = "https://github.com/cardoe/cargo-ebuild"
readme = "README.md"
keywords = ["cargo-subcommand", "ebuild", "gentoo"]
categories = ["command-line-utilities"]
description = """
Generates an ebuild for a package using the in-tree eclasses.
"""

[badges.travis-ci]
repository = "cardoe/cargo-bitbake"

[dependencies]
cargo = "^0.27"
time = "^0.1"
structopt = "^0.2"
quicli = "^0.2"
